"""
Philippines 2024 — 6-month lookback split into 3-month windows.

For each collection date in CWBD_PHL.csv the script:
  1. Downloads / loads a multi-variable climate NetCDF for the Philippines.
  2. Looks back 180 days (6 months) from the collection date.
  3. Splits that window into two non-overlapping 3-month periods:
       • period_m1_m3  →  T−90  to  T      (most recent 3 months)
       • period_m4_m6  →  T−180 to  T−91   (earliest  3 months)
  4. Computes meteorological summaries + climate indices for EACH period.
  5. Extracts values at the observation points.
  6. Saves combined features to data/processed/phl_2024_climate_windows.parquet

Run from the WitchesBroom root:
    python -m notebooks.phl_2024_temporal_windows
"""

import sys
import os
from datetime import datetime, timedelta
from pathlib import Path

import numpy as np
import pandas as pd
import geopandas as gpd
import xarray
from tqdm import tqdm

# ── make src importable ────────────────────────────────────────────────────
ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.features.climate_indices import calculate_indices
from src.features.met_summaries import calculate_meteorological_summaries
from src.utils.spatial_utils import extracting_using_gpdf

# ══════════════════════════════════════════════════════════════════════════════
# 1.  CONFIGURATION
# ══════════════════════════════════════════════════════════════════════════════

# Philippines bounding box: [xmin, ymin, xmax, ymax]
PHL_EXTENT = [121.0, 7.0, 126.0, 18.0]

# Climate NetCDF path (generated by download step below)
CLIMATE_NC = "outputs/climate_data/weather_phl_2024.nc"

# 6-month lookback and 3-month window size (in days)
LOOKBACK_DAYS = 180
WINDOW_DAYS   = 90   # each 3-month period

# Variable summaries to compute for each window
VARIABLES_DICT = {
    "temp_accum":    ["tmean"],
    "hr_accum":      ["dailyhr"],
    "hr06_accum":    ["hr06"],
    "hr09_accum":    ["hr09"],
    "hr12_accum":    ["hr12"],
    "hr15_accum":    ["hr15"],
    "hr18_accum":    ["hr18"],
    "dewtemp_accum": ["dpt"],
    "vpd_accum":     ["vpd"],
    "etr_accum":     ["etr"],
    "srad_accum":    ["srad"],
    "prec_accum":    ["precipitation"],
}

# Climate indices to compute for each window
INDICES_DICT = {
    "vpd_lt_15":              ["vpd", 1.5],
    "n_vpd_spells":           ["vpd", 1.5, 7],
    "n_wet_spells":           ["precipitation", 1.0, 7],
    "n_dry_spells":           ["precipitation", 1.0, 7],
    "avg_wet_spell_duration": ["precipitation", 1.0, 7],
    "avg_dry_spell_duration": ["precipitation", 1.0, 7],
    "rh_85_90_days": [
        ["dailyhr", "hr06", "hr09", "hr12", "hr15", "hr18"],
        [85, 90], [">=", "<="]
    ],
    "tmean_25_30_days":      ["tmean", [25, 30], [">=", "<="]],
    "max_temp_days":         ["tmax", 32],
    "precip_max_15d":        ["precipitation"],
    "max_hr_days":           ["dailyhr", 80],
    "consecutive_dry_days":  ["precipitation", 1.0],
    "growing_degree_days":   ["tmean", 15],
    "daily_intensity_index": ["precipitation", 1.0],
    "disease_pressure_index": ["vpd"],
}

# ══════════════════════════════════════════════════════════════════════════════
# 2.  STEP 1 – CLIMATE DATA DOWNLOAD  (run once, skip if file already exists)
# ══════════════════════════════════════════════════════════════════════════════

def download_phl_climate():
    """
    Download AgEra5 + CHIRPS for the Philippines 2024.

    The download must cover 6 months before the earliest collection date
    (2024-04-02) through the latest collection date (2024-09-18).

    Requires ag-cube-cm / WeatherSoilDataProcessor installed.
    """
    from src.data.download_climate import ClimateDataFetcher, stack_datacube_temporally, set_encoding
    from spatialdata.files_manager import IntervalFolderManager
    from spatialdata.climate_data import MLTWeatherDataCube

    # Cover Oct 2023 → Sep 2024  (gives full 6-month lookback for all dates)
    fetcher = ClimateDataFetcher(
        starting_date="2023-10-01",
        ending_date="2024-09-30",
        xyxy=PHL_EXTENT,
        output_folder="outputs/climate_data",
    )

    agera5_vars = {
        "temperature_tmax":     {"mission": "agera5", "source": "agera5"},
        "temperature_tmin":     {"mission": "agera5", "source": "agera5"},
        "solar_radiation":      {"mission": "agera5", "source": "agera5"},
        "relative_humidity_06": {"mission": "agera5", "source": "agera5"},
        "relative_humidity_09": {"mission": "agera5", "source": "agera5"},
        "relative_humidity_12": {"mission": "agera5", "source": "agera5"},
        "relative_humidity_15": {"mission": "agera5", "source": "agera5"},
        "relative_humidity_18": {"mission": "agera5", "source": "agera5"},
    }
    chirps_vars = {
        "precipitation": {"mission": "chirps", "source": "chirps"},
    }

    fetcher.download_agera5(agera5_vars, suffix_output_folder="phl", ncores=5)
    fetcher.download_chirps(chirps_vars,  suffix_output_folder="phl", ncores=5)

    # Stack raw tiles into a single NetCDF
    raw_paths = {
        "precipitation": "outputs/climate_data/precipitation_phl_raw",
        "tmin":          "outputs/climate_data/temperature_tmin_phl_raw",
        "tmax":          "outputs/climate_data/temperature_tmax_phl_raw",
        "srad":          "outputs/climate_data/solar_radiation_phl_raw",
        "hr06":          "outputs/climate_data/relative_humidity_06_phl_raw",
        "hr09":          "outputs/climate_data/relative_humidity_09_phl_raw",
        "hr12":          "outputs/climate_data/relative_humidity_12_phl_raw",
        "hr15":          "outputs/climate_data/relative_humidity_15_phl_raw",
        "hr18":          "outputs/climate_data/relative_humidity_18_phl_raw",
    }

    folder_mgr = IntervalFolderManager()
    cube = MLTWeatherDataCube(raw_paths, folder_mgr)
    cube.common_dates_and_file_names("2023-10-01", "2024-09-30")
    mlt_data = cube.multitemporal_data(reference_variable="precipitation", ncores=0)

    # Unit conversions
    mlt_data_conv = {}
    for d, ds in mlt_data.items():
        ds["srad"] = ds["srad"] / 1_000_000   # J → MJ m⁻² d⁻¹
        ds["tmax"] = ds["tmax"] - 273.15       # K → °C
        ds["tmin"] = ds["tmin"] - 273.15
        mlt_data_conv[d] = ds

    stacked = stack_datacube_temporally(mlt_data_conv, time_dim_name="date")
    encoding = set_encoding(stacked)
    stacked.to_netcdf(CLIMATE_NC, encoding=encoding, engine="netcdf4")
    print(f"Climate cube saved → {CLIMATE_NC}")


# ══════════════════════════════════════════════════════════════════════════════
# 3.  HELPER – build derived variables (tmean, dailyhr)
# ══════════════════════════════════════════════════════════════════════════════

def prepare_derived_vars(ds: xarray.Dataset) -> xarray.Dataset:
    """Add tmean, dailyhr to the dataset.  Assumes tmax/tmin in °C."""
    ds = ds.copy()
    ds["tmean"]   = (ds["tmax"] + ds["tmin"]) / 2
    ds["dailyhr"] = (
        ds[["hr06", "hr09", "hr12", "hr15", "hr18"]]
        .to_array(dim="hour")
        .mean(dim="hour")
    )
    return ds


# ══════════════════════════════════════════════════════════════════════════════
# 4.  HELPER – slice one temporal window and return (summaries, indices) DS
# ══════════════════════════════════════════════════════════════════════════════

def compute_window(ds_full: xarray.Dataset,
                   start: datetime, end: datetime,
                   label: str) -> xarray.Dataset:
    """
    Slice *ds_full* to [start, end], add derived vars, and compute
    meteorological summaries + climate indices.

    All output variable names are prefixed with *label* so that results
    from different windows can be merged without collision.
    """
    window = ds_full.sel(date=slice(start, end))
    window = window.set_index(date="date").rename({"date": "time"})
    window = prepare_derived_vars(window)

    summaries = calculate_meteorological_summaries(window, VARIABLES_DICT)
    indices   = calculate_indices(window, INDICES_DICT)
    merged    = xarray.merge([summaries, indices])

    # Prefix all variables with the window label
    return merged.rename({v: f"{label}__{v}" for v in merged.data_vars})


# ══════════════════════════════════════════════════════════════════════════════
# 5.  LOAD OBSERVATIONS
# ══════════════════════════════════════════════════════════════════════════════

def load_observations(csv_path: str) -> gpd.GeoDataFrame:
    """
    Read CWBD_PHL.csv and compute per-location disease frequency.

    Returns a GeoDataFrame with one row per unique (location, date) pair
    and a numeric disease_incidence column (0–1).
    """
    df = pd.read_csv(csv_path)
    df["collection_date"] = pd.to_datetime(
        df["collection_date"].astype(str), format="%Y%m%d"
    )

    # Normalise VS to binary: P=1, any other=0
    df["presence"] = (df["VS"].str.upper() == "P").astype(int)

    # Unique location key
    df["loc_key"] = df["latitude"].astype(str) + "_" + df["longitude"].astype(str)

    # Per-(location, date) symptom frequency
    grouped = (
        df.groupby(["loc_key", "collection_date", "latitude", "longitude"])
        ["presence"]
        .agg(disease_incidence="mean", n_obs="count")
        .reset_index()
    )

    return gpd.GeoDataFrame(
        grouped,
        geometry=gpd.points_from_xy(grouped.longitude, grouped.latitude),
        crs="EPSG:4326",
    )


# ══════════════════════════════════════════════════════════════════════════════
# 6.  MAIN  –  iterate over collection dates, build window features
# ══════════════════════════════════════════════════════════════════════════════

def main():
    # ── Load observations ─────────────────────────────────────────────────
    obs = load_observations("data/raw/CWBD_PHL.csv")
    collection_dates = sorted(obs["collection_date"].unique())
    print(f"Loaded {len(obs)} observation records across {len(collection_dates)} dates.")

    # ── Download climate data if needed ───────────────────────────────────
    if not Path(CLIMATE_NC).exists():
        print("Climate file not found — starting download (this takes ~30 min)…")
        download_phl_climate()

    # ── Open climate cube ─────────────────────────────────────────────────
    print(f"Opening climate cube: {CLIMATE_NC}")
    climate_ds = xarray.open_dataset(CLIMATE_NC)

    # Unit conversions (if not already done during stacking)
    if climate_ds["vpd"].max() > 10:             # still in hPa
        climate_ds["vpd"] = climate_ds["vpd"] * 0.1
    if climate_ds["dpt"].max() > 100:            # still in Kelvin
        climate_ds["dpt"] = climate_ds["dpt"] - 273.15

    print(climate_ds)

    # ── Main processing loop ──────────────────────────────────────────────
    results = []

    for cdate in tqdm(collection_dates, desc="Collection dates"):
        # Define temporal windows
        t0 = pd.Timestamp(cdate)
        windows = {
            "m1_m3": (t0 - timedelta(days=WINDOW_DAYS),       t0),                               # T-90  … T
            "m4_m6": (t0 - timedelta(days=LOOKBACK_DAYS),     t0 - timedelta(days=WINDOW_DAYS+1)),# T-180 … T-91
        }

        # Observations for this date
        date_obs = obs.loc[obs["collection_date"] == cdate].copy()
        if date_obs.empty:
            continue

        # Compute features per window
        window_dss = {}
        for label, (wstart, wend) in windows.items():
            try:
                window_dss[label] = compute_window(climate_ds, wstart, wend, label)
            except Exception as e:
                print(f"  [warn] {cdate} / {label}: {e}")

        if not window_dss:
            continue

        # Merge both windows into one spatial dataset, then extract at points
        combined_ds = xarray.merge(list(window_dss.values()))
        date_obs_str = date_obs.copy()
        date_obs_str["collection_date"] = cdate.strftime("%Y%m%d")

        extracted = extracting_using_gpdf(date_obs_str, combined_ds)
        results.append(extracted)

    # ── Combine and save ──────────────────────────────────────────────────
    if not results:
        print("No results produced — check climate data coverage.")
        return

    final = gpd.GeoDataFrame(
        pd.concat(results, ignore_index=True),
        geometry=pd.concat(results, ignore_index=True).geometry,
        crs="EPSG:4326",
    )

    out_path = "data/processed/phl_2024_climate_windows.parquet"
    Path("data/processed").mkdir(parents=True, exist_ok=True)
    final.to_parquet(out_path)
    print(f"\nSaved {len(final)} rows × {len(final.columns)} columns → {out_path}")

    # Quick column summary
    window_cols = [c for c in final.columns if c.startswith("m1_m3__") or c.startswith("m4_m6__")]
    print(f"\n  m1_m3 features : {sum(1 for c in window_cols if c.startswith('m1_m3__'))}")
    print(f"  m4_m6 features : {sum(1 for c in window_cols if c.startswith('m4_m6__'))}")
    print(f"\nSample output:\n{final[['collection_date', 'latitude', 'longitude', 'disease_incidence'] + window_cols[:4]].head()}")

    return final


if __name__ == "__main__":
    main()
